export interface TumorCode {
  tumor_code: string,
  case_id: string,
  discovery_study: string,
  "discovery_study/analyzed_samples": string,
  confirmatory_study: string,
  gender: string,
  age: string,
  height_in_cm: string,
  weight_in_kg: string,
  BMI: string,
  race: string,
  ethnicity: string,
  tumor_site: string,
  tumor_size_in_cm: string,
  histologic_type: string,
  histologic_grade: string,
  tumor_stage_pathological: string,
  AJCC_or_TNM_cancer_staging_edition: string,
  pathologic_staging_primary_tumor_pT: string,
  pathologic_staging_regional_lymph_nodes_pN: string,
  pathologic_staging_distant_metastasis_pM: string,
  clinical_staging_distant_metastasis_cM: string,
  vital_status_at_12months_follow_up: string,
  vital_status_at_24months_follow_up: string,
  residual_tumor: string,
  alcohol_consumption: string,
  tobacco_smoking_history: string,
  number_of_pack_years_smoked: string,
  tumor_status_at_12months_follow_up: string,
  tumor_status_at_24months_follow_up: string,
  days_from_initial_diagnosis_to_last_contact_at_12months_follow_up: string,
  days_from_initial_diagnosis_to_last_contact_at_24months_follow_up: string,
  specimens: [
    {
      specimen_id: string,
      slide_id: string,
      tissue_type: string,
      percent_tumor_surface_area: string,
      percent_tumor_nuclei: string,
      percent_necrotic_surface_area: string,
      weight_in_mg: string,
    }
  ],
  inserted: string,
  updated: string,
}
